version: '3'

services:
  geolineo:
    image: dr.duftetechnik.de/gpt/geolineo
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      - ROCKET_PORT=80
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_SECRET_KEY=K+zoMg81kAS6qOF3Kx+W2rSIbndyHOjnk5mJrbTWgjU=
      - ROCKET_WORKERS=2
      - ROCKET_TEMPLATE_DIR=/etc/geolineo/templates
      - RUST_LOG=debug
      - TEST_CASES_SUBDIRECTORY=/etc/geolineo/test_cases
