version: '3'

services:
  geolineo:
    image: dr.duftetechnik.de/gpt/geolineo
    restart: unless-stopped
    expose:
      - 80
    environment:
      - ROCKET_PORT=80
      - ROCKET_SECRET_KEY=K+zoMg81kAS6qOF3Kx+W2rSIbndyHOjnk5mJrbTWgjU=
      - ROCKET_WORKERS=2
      - TEST_CASES_SUBDIRECTORY=./geoleo/tests/test_cases


